version: "3"

services:
  cloudflared:
    container_name: cloudflared
    image: visibilityspots/cloudflared
    restart: always
    networks:
      pihole_net:
        ipv4_address: 10.0.0.2

  pi-hole:
    container_name: pi-hole
    image: pihole/pihole
    restart: always
    hostname: pihole
    ports:
      - "8000:80/tcp"
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - "${HOME}/Documents/dockerData/pihole/etc-pihole/:/etc/pihole"
      - "${HOME}/Documents/dockerData/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d"
      - "/dev/null:/var/log/pihole.log:ro"
    environment:
      - PIHOLE_DNS_=10.0.0.2#5054;1.1.1.2#53
      - IPv6=false
      - TZ=Europe/London
      - DNSMASQ_LISTENING=all
      - WEBPASSWORD=admin
      - PIHOLELOG=/dev/null
    networks:
      pihole_net:
        ipv4_address: 10.0.0.3
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN

networks:
  pihole_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/29