version: '3.5'

services:
  headscale:
    image: headscale/headscale:latest
    command: headscale serve
    restart: unless-stopped
    stop_grace_period: 10s
    ports:
      - 443:443
      - 9090:9090
    env_file:
      - ./.env
    environment:
      SOME_ENV: 0000
    volumes:
      - "${HOME}/Documents/dockerData/headscale/config:/etc/headscale/"
