version: "3.3"

services:

  heimdall:
    image: "lscr.io/linuxserver/heimdall:latest"
    container_name: "heimdall"
    restart: unless-stopped
    ports:
      - "80:8080"
      - "443:8443"
    volumes:
      - "${HOME}/Documents/dockerData/heimdall/config:/config"
    environment:
      - PUID=1000
      - PGID=1000
    env_file:
      - ./.env
