version: '3'
services:
  watchtower:
    container_name: portainer-server
    image: portainer/portainer-ce:latest
    restart: always
    ports:
      - 8000:8000
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    env_file:
      - ./.env