version: '3'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: always
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    env_file:
      - ./.env
    environment:
      - TZ=America/New_York
      # PLEX_CLAIM=yourclaimtoken
      # ADVERTISE_IP=youradvertiseip
    hostname: aayla
    volumes:
      - ${HOME}/Documents/dockerData/plex/database:/config
      - ${HOME}/Documents/dockerData/plex/transcode:/transcode
      - ${HOME}/Documents/dockerData/plex/media:/data
      - ${HOME}/Documents/dockerData/letsencrypt/config/etc/letsencrypt:/le-ssl
