version: "3"

services:
  letsencrypt:
    container_name: letsencrypt
    image: linuxserver/letsencrypt
    restart: always
    ports:
      - "443:443"
      - "80:80"
    env_file:
      - ./.env
    environment:
      PUID: '1000'
      PGID: '1000'
      TZ: 'America/Chicago'
      SUBDOMAINS: 'wildcard'
      VALIDATION: 'duckdns'
      # DUCKDNSTOKEN: 'your duckdns token'
      # URL: 'your urls'
    # Volumes store your data between container upgrades
    volumes:
      - '${HOME}/Documents/dockerData/letsencrypt/config:/config'
