version: '3'
services:
  qbittorrent:
    container_name: qbittorrent
    image: linuxserver/qbittorrent
    restart: always
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8001:8001
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - UMASK_SET=022
      - WEBUI_PORT=8001
    volumes:
      - ${HOME}/Documents/dockerData/qbittorrent/config:/config
      - ${HOME}/Documents/dockerData/qbittorrent/downloads:/downloads
